### ISSUE TITLE
iCloud v3 Beta Testers List - Latest: Beta 14 (3/9/2923)

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3_v3#2]
### Beta 14 was just released
Download it from the [Release page here](https://github.com/gcobb321/icloud3_v3/releases). Select Assets, then select icloud3-beta-#.zip)

### New Testers
Please add your username to this thread so I can easily notify you of any updates. Also add a comment to this Issue. Then you will be notified when a new version is available. It will also help me keep track of who is testing it and the number of people that are giving it a try.

Do not download from HACS. The beta is not available on HACS. If you download from HACS, v2.4.7 will overwrite the iCloud3 directory, wiping out the v3 beta and you will have to start over.

### Important Links
- iCloud3 v3 Documentation can be found [here](https://gcobb321.github.io/icloud3_v3_docs/#/)
- Download from the [Release page here](https://github.com/gcobb321/icloud3_v3/releases). Select Assets, then select icloud3-beta-#.zip. or,
- All of the Change Logs can be found [here](https://github.com/gcobb321/icloud3_v3/blob/v3.0.0-beta-14/custom_components/icloud3/ChangeLog.txt)

I'll post a notice to this Issue when a new beta version is available. I'll add it to the bottom of this Issue and it will list of what changed.

Thanks
Gary.

**Comment by garyak** [comment]
garyak will be testing.

**Comment by hvddrift** [comment]
Hans is on the test

**Comment by poudenes** [comment]
Peter (poudenes > on GitHub and HA)

**Comment by marceloaf** [comment]
marcelof will be testing as well

**Comment by JtwoA** [comment]
Commencing with testing.

**Comment by bradgonzalez** [comment]
bgnzo is available to test

**Comment by bgnzo818** [comment]
bgnzo available for testing

**Comment by gcobb321** [comment]
Beta 2 has been posted. You will find it [here](https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0.0-beta-2)

Beta 2 change log:
------------
1.  Do not display an error messgage when trying to get the model of a device if t is
    not in the HA device registry. (entity_io:137)
2.  Fix a problem checking if info for all of configured devices that had been set
    up had been returned from iCloud account during startup. If not, the FmF devices
    were being refreshed when it should be refreshing the FamShr devices. (start_ic3:1315)
3.  Fixed an error copying the Event Log image sample files to the custom cards directory.
    It was copyingthe files from 'event_log' instead of 'event_log_card'. (start_ic3:722)
4.  Added 'Erase All Devices' to the Configuration > Action menu that will reinitialize the
    iCloud3 Devices List.
5.  The Time Format (12/24-hour) was converted incorrectly. It was creating '12/24-hour-hour'
    This has been fixed and the invalid parameter in the configuration file was corrected.
6.  Fixed a problem where a check was being made to see if 2fa authentication was needed when
    the connection to the iCloud Location Services had not been completed, causing a problem
    with the parameter migration (icloud_main:732).
7.  Reformatted the items written to the icloud3_migration.log file for clarity.
8.  Fixed a problem shrinking the Event Log (event_log:538 recursion error).
9.  Fixed a problem when Family Sharing info from iCloud Location Services had not completely
    loaded during initialization and was generating an error during the retry operation (start_ic3:1113).
10. Fixed a problem, hopefully, that was generating the HA Blocking error when starting up the iCloud Location Services interface. This was also occurring (sometimes) when logging into a new the iCloud account from the Configurator.

**Comment by avd706** [comment]
Hi. Please let me try. Do we use the b1?Is that the latest?

**Comment by gcobb321** [comment]
No. [Beta 2](https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0.0-beta-2)

**Comment by avd706** [comment]
> No. [Beta 2 here](https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0.0-beta-2)

Got it, didn't see it, but saw references to it. Thanks.

**Comment by gcobb321** [comment]
Ho Ho Ho. Happy holidays. 🎄🎅

If you don’t have plans, enjoy [iCloud3 v3.0.0 beta 3](https://github.com/gcobb321/icloud3_v3/releases)

Gary

**Comment by gcobb321** [comment]
Ho. Ho. Ho. Happy holidays.🎄🎅

If you don’t have any plans, enjoy [iCloud3 v3.0.0 beta 3](https://github.com/gcobb321/icloud3_v3/releases/tag/v3.0.0-beta-3)

Beta 3 - 12/24/2022

1. Fixed a problem where the Configurator > Sensors would generate an 'Unknown Error Ocurred'
error message. This was caused by an invalid sensor field name ('tracking_from_zones')
in the configuration file.
2. Fixed a problem on the Configurator > Sensors screen dealing with an invalid 'battery_status'
error message.
3. Fixed a problem where error messages were displayed getting device info from the HA device
registry when the device was not in the registry.
4. Fixed a problem displaying the obscured email address if there was more than one @-sign
in the address.
5. Added 'Reinitialize All Devices' to the Configurator > iCloud3 Devices screen. With it,
you can remove all devices from iCloud3 or reset the selections for the iCloud FamShr & FmF
and the iOS App parameters to None. This will clear any errors due to device migration errors.
6. Setting up the log_level (info, debug, rawdata) a lot earlier. It is now setup when HA loads iCloud3
instead of later. Debug and RawData information should now be written to the HA Log file
(home-assistant.log) when the iCloud Account connection is first established.
7. Moved Event Log Configuration option to Menu Page 1 and moved Display Text As option to Menu
Page 2. Also added the Log Level parameter to the Event Log Configuration screen. This
will reduce the steps needed to change the Log Level parameter when debug/rawdata logging
is desired. ---> YOU MAY NEED TO REFRESH YOUR BROWSER WITH THE CONFIGURATOR OPEN <---
8. Fixed problem changing the devices Friendly Name that would generate an error message deleting
tracking_from_zone sensors when they had not been created.
9. The device_tracker state value is now lower-case.
10. Log level debug and rawdata records are now written to the '/config/icloud3_debug.log' file
instead of the HA log file. A new file is created every time HA starts.
11. The file extension for the Event Log file was changed from '.txt' to '.log'. The file name is now
'icloud3-event-log_[time].log'.

**Comment by pauly7300** [comment]
Pauly7300 Testing.  Loving it so far.

**Comment by mobiledude** [comment]
Mobiledude testing

**Comment by chupacabra71** [comment]
installed and testing.

**Comment by gcobb321** [comment]
**Beta 4 is alive and ready to be downloaded.** 

It fixes a few things, add a few others and finalizes the icloud3-debug.log handling. I also have a question at the end about the naming of the Event Log exported file...should it have the date as part of the file name so every export is unique or should it just be 'icloud3-event-log.log' so each export overwrites the previous one.

The change log follows and has fewer items than beta 3. Yea, and thanks to all.

**Beta 4 - 12/17/2022**
1.  Inactive/Untracked devices are listed at the end of the Startup Event Log messages.
2.  Fixed some problems displaying the EVent Log when there were no devices to track.
3.  Fixed problem dealing with Gb.ic3_debug_log_write_secs variable not found.
4.  Fixed problem where the Event Log records were not displayed in a timely manner when starting.
5.  The tracking results written to the Log file now include the zone, distance and time values.
6.  Reworked the icloud3-debug.log file:
        - A new file is created when:
            - HA/iCloud3 starts and the Log Level is debug or rawdata or
            - Starting Debug Logging from Event Log > Actions or
            - At midnight when debug logging is on and the file is more thn 20-hours old.
        - Otherwise debug records are added to the existing Debug Log file.
        - If the Log Level is debug or rawdata in the Configurator > Event Log parameters and
          Stop Debug Logging was selected on Event Log > Actions, the ic3 config will be changed
          to 'info' (no debug logging).
        - If the configuration is set to 'info' (no debug logging) and it is started on 
          Event Log > Actions, the configuration is not updated and the debug logging will 
          remain on until midnight, the next iCloud3 restart or when it is turned off.


QUESTION: Currently the Exported Event Log file contains the date/time indicating when it was created.
          This creates a new file for every export.
                Example: 'icloud3-event-log_2022-12-26 18:00:00.log'
          Another option is to not have the date/time in the file name so a new Export overwrites 
          the last one.
                Example: 'icloud3-event-log.log'

          Does anyone have an opinion on this.

**Comment by JtwoA** [comment]
I like having the datestamp in the file name.

**Comment by broyuken** [comment]
Im testing as well

**Comment by gcobb321** [comment]
**Oops.** I forgot to change the iCloud3 beta version number from b3 to b4 on the update. I fixed that but have not created a new release. Just download beta 4 again.

**Comment by marceloaf** [comment]
Hi Gary, good morning.

I’m having a hard time to upgrade from 2.4.7 to 3.0 so I have decided to start from scratch using a virtual machine.

After installing Beta4 I restarted HA. After restart and trying to login to my apple account it get stuck with the spinning circle and never goes to the next page, although I still receive and apple icloud notification that someone is trying to log in to my account.
***@***.***


I tried to delete both icloud and icloud3 folders under .storage folder and restart but it didn’t work.

Thanks in advance,
Marcelo Franco

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by gcobb321** [comment]
Marcelo,
1. FYI-The config/.storage/icloud directory contains the icloud account 
cookies & session verification info so there is no need to delete that. 
The config/.storage/icloud3 contains the icloud3 parameter and utility 
files.
2. On the restart, does it show any errors in the HA log file?
3. Did you go to the iCloud Account Login Credentials screen and select 
Login or something else? AppleID/password OK?
4. Did the HA Notifications show an alert (orange bell) that indicates 
the verification code is needed? If Yes, select it and enter the 
verification code. Maybe it was waiting for the code to be entered (The 
spinning circle indicates HA is waiting for something to happen since it 
has control at that point).
5. What does restarting HA do? I do not know what running on a virtual 
machine would do?
6. Restart HA and go to iCloud3 Configurator > Event Log Configuration. 
Change Log Level to Rawdata. This will dump the iCloud Account rawdata 
to /config/icloud3-debug.log and show all the network traffic between 
you and your iCloud account.
7. Restart HA again to start the Debug Log from scratch.
8. See if you are logged into your iCloud account. Make sure you can 
enter the 6-digit verification code. Check the iCloud3 Devices screen to 
see if your devices are listed.
9. Can you see the Event Log screen (iCloud3 v3) is the on the title 
line at the top? if yes, do Actions > Export Event Log.

email the icloud3-event-log_[datetime],log and icloud3-debug,log to 
***@***.*** and I'll take a look at them.


Gary Cobb


------ Original Message ------
From "marceloaf" ***@***.***>
To "gcobb321/icloud3_v3" ***@***.***>
Cc "Gary Cobb" ***@***.***>; "Author" 
***@***.***>
Date 12/28/2022 9:12:52 AM
Subject Re: [gcobb321/icloud3_v3] iCloud v3.0.0 Beta - User List (Issue 
#2)

**Comment by pauly7300** [comment]
For me, the primary reason I have referenced the previous version of the
icloud3-event log file was for comparison.  IE, to see if a change I made
to a config produced a different outcome.  I guess my preference would be
to keep the current behavior.  Cleaning up (deleting) the old ones really
isn't that much overhead.  Anyone that cares enough to generate an
ic3-event-log knows where it is and it doesn't seem like a hassle to remove
unwanted versions but of course that's just one opinion.

**Comment by gcobb321** [comment]
**I just uploaded Beta 5** -- It fixes a error message that is displayed sometimes at start up, adds some enhancements to the Event Log and updates the Event Log Lovelace card that will require a browser refresh on all devices running HA (you will see a message on each device with instructions for that device).

The exported Event Log log report name stays as it is. The vote was 2 (don't mess with the name) to 0 (one EvLog file is plenty). Thanks for the feedback.

Here is the Change List (2 minor bugs fixed, 2 enhancements to the Event Log):
1.  Fixed a 'log_info_msg' not defined error message in the routine that identifies the notify
    service  used for a device. This is just an informative message indicating HA has not set it
    up yet.
2.  Periodically, the events currently displayed for a device is reduced from all events to less
    than a screen. This number was increased from 1/2-screen to about 2-screens.
3.  When the displayed events for a device were reduced (#2 above), the screen was never refreshed so you would always see the old events and had to do a refresh to see the latest events. Now, the device's events are automatically refreshed when they are updated.
4.  Updated the Event Log Lovelace card to v3.0.1. This fixes a problem when the date/time should not  be displayed if there was an alert message was displayed.

**Comment by marceloaf** [comment]
I was just about to send all the logs from the tests I did with Beta4 but I will try again tomorrow with Beta5. Thanks

**Comment by gcobb321** [comment]
@marceloaf  Go ahead and send them. The items i fixed probably would not have anything to do with your issues.

**Comment by marceloaf** [comment]
Hi Gary. Here they are.

My responses are below. Just for your information I created a brand new Home assistant environment in a virtual machine running on Virtual Box. The only addons I’m running are SAMBA, DuckDns and NGINX. I registered a specific duckdns domain for this test and configured my router and certificates to enable login using https from outside. A bit suspicious NGINX throwing some errors at the same time I was trying to authenticate in icloud through icloud3

I also tried to cover my apple credentials in the logs… 😊

I’m not sure if the attachment is also posted on github. If so, could you please delete them from the thread?

Many thanks in advance

**Comment by pauly7300** [comment]
Gary, maybe i'm downloading the wrong thing but the descriptions on the zip files in the beta archive seem like they're off.  Beta 4a has a description of 'Beta 5'.  
<img width="1699" alt="image" src="https://user-images.githubusercontent.com/11494052/209896131-806a6317-c011-43db-913c-09f251046211.png">

**Comment by gcobb321** [comment]
@pauly7300 
That refers to the description of the update, not the file to download. 

Download from the Release page [here](https://github.com/gcobb321/icloud3_v3/releases). Select _Assets_, then select _icloud3-beta-#.zip._  or,
Download directly from the Code page [here](https://github.com/gcobb321/icloud3_v3/blob/main/icloud3-beta-5.zip)

**Comment by gcobb321** [comment]
**Beta 6, Beta 6, Beta 6** - It's the weekend so, now that the holidays are almost over, it's time to download the latest beta version. This fixes a few minor issues, makes sure the Debug Log is recreated when iCloud3 is restarted, adds an autorefresh function to the Event Log, speeds up the display of the Initial Locate and a few other things. Details are below.

Download from the [Release page here](https://github.com/gcobb321/icloud3_v3/releases). Select *Assets*, then select icloud3-beta-#.zip. or,
Download directly from the [GitHub Code page here](https://github.com/gcobb321/icloud3_v3/blob/main/icloud3-beta-6.zip). Click *download* on the right side of the screen.

Change Log:
1.  Corrected a mispelled directory name used for installing sample device images (ipad.png, watch.png). The image directory nane was 'event_log_cad'. It should be 'event_log_card'.
2.  A new icloud3-debug.log file will now be created when restarting iCloud3 from the Event Log or when HA was started and the log level is debug. New records will be added to the existing log file when debug is started from Event Log > Actions and the log file is less than 20-hours old.
3.  Fixed a problem where location data from iCloud FamShr/FmF was not always being rejected due to poor gps_accuracy. This could lead to location & zone errors until the next locate was processed.
4.  Improved the performance displaying the results of the Initial Device Locate results in the Event Log.
5.  The Event Log for the selected devices is automatically refreshed when new information is added. The number of items was increased from 15 to 50 so more events are displayed without refreshing.
6.  Added a prefilter to the rawdata debug log to make sure usernames & passwords are not displayed.
7.  Some internal code cleanup and minor tweaking.

**Comment by gcobb321** [comment]
Thanks everyone for helping me make sure iCloud3 is as solid as a rock. I appreciate your comments, suggestions and working through some of the things you have found. 

Wishing you all the best for 2023.

![Happy New Year](https://user-images.githubusercontent.com/35449479/210157805-e5a95263-c421-496c-a86a-3b33d00cf866.GIF)

**Comment by JtwoA** [comment]
Thanks for building this out, it’s much appreciated.  Have a great 2023 as well.

**Comment by diothar** [comment]
Was dealing with an all hands-on-deck hot ticket at work for the last few weeks, but I am now clear to test.  Please sign up diothar for testing if possible.

**Comment by derekoharrow** [comment]
Testing. Thanks!

**Comment by confusedsecuritydudes** [comment]
Testing.

**Comment by beyondwatts** [comment]
Testing, looking good!

**Comment by lukkigi** [comment]
I will be testing as well

**Comment by J-Fartz** [comment]
J-Fartz is testing

**Comment by gcobb321** [comment]
**Beta 8, Beta 8, Beta 8** 
- Fixed the problem accessing the iCloud3 Devices screen. Again. I hope. The problem is a timing issue and an issue between HA and requesting data from the iCloud Account. I tried a completely new approach and hope it works this time.
- The Waze server selection method was changed so it is in line with how Waze does it. (US/Canada, Israel, Rest of the World).
- The battery and battery status updates have been fixed so the battery level is reported every 15-seconds like it was suppose to have been.
- Fixed an when 3 or more devices where sharing their location and iCloud3 would stop updating everyone's location.
- And a few more issues..

See the change list below for the details.

Download from the [Release page here](https://github.com/gcobb321/icloud3_v3/releases). Select Assets, then select icloud3-beta-#.zip. or,
Download directly from the [GitHub Code page here](https://github.com/gcobb321/icloud3_v3/blob/main/icloud3-beta-8.zip). Click download on the right side of the screen.
All of the Change Logs can be found [here](https://github.com/gcobb321/icloud3_v3/blob/v3%2C0%2C0-beta-8/custom_components/icloud3/ChangeLog.txt)

**Change Log**
1.  Fixed the bug accessing the iCloud3 Devices screen. Again. I hope. It is a timing issue and an
    issue with accessing the iCloud Account through HA. I could make it fail yesterday but not today
    when trying to verify that the new approach fixed it. For those that are having this problem,
    please let me know if you are still having a problem and I'll take another crack at it.
2.  The Waze Route Service is handled by 3-servers around the world - United States/Canada, Israel,
    and the Rest of the World. The HA Country Code is now used to determine that
    the appropriate server is used. It is still shown on the Waze configuration screen for
    information only. It is verified and corrected when HA starts if the wrong server is selected.
3.  Combined the configuration screens for the Waze Route Server and Waze History Database into one
    screen. THIS MAY REQUIRE A BROWSER CACHE REFRESH
4.  Added the 'iCloud3 Theme' that tweeks the field labels in the Configurator so the descriptive
    text is a little more readable (at least for me with my old eyes). It has both a light and dark
    mode and only a few entries. You can find the it in config/custom_components/icloud3/theme.

    Move the 'iCloud3 Theme' from the 'icloud3/theme' folder to the 'config/themes' folder.
    (1) If you are already using a theme, copy the 'icloud3_theme.yaml' file statements (both the
        light and dark mode) into the appropriate location in your theme's yaml file. Then restart HA.
    (2) If you are not using a theme, restart HA, open your Profile screen, then select 'iCloud3 Theme'
    on the Themes list.

    I used it when capturing screenshots for the iCloud3 documentation.
5.  Fixed a number of problems with the battery and battery status sensors. (1) It was being updated
    by the iOS App every 15-minutes instead of every 5-seconds. (2) The value was resetting to 0 when
    HA or iCloud3 restarted instead of restoring it's value from the last update. (3) It was not being
    updated when iCloud3 restarted until the next poll, which may be 2-hours if you are in a zone.
    (4) It was only being saved to the restore_state file on the next poll, not the value when it
    changed in the iOS App. Again, if you are in a zone, the value might be 2-hours old from the last
    iCloud update, leading to drops and spikes in the battery sensor in the HA history.
6.  Fixed a problem that might cause iCloud3 to hang when you are tracking 2 or more devices and they
    are all close to eack other. The problem occured when device A was using device B tracking results
    (distance, travel time, next update time, etc), B was using C, and C was using A. This created a
    circular loop so every device used the same data and a new update was never done.
7.  Addressed a problem building the picture file list for the iCloud3 Devices screen. I can not
    reproduce the error but changed some code so the error being encountered would not occur.

**Comment by derekoharrow** [comment]
After upgrading from b7 to b8 I'm getting the following errors constantly in the HA log file:

```
2023-01-14 22:08:05.084 ERROR (SyncWorker_10) [icloud3] invalid literal for int() with base 10: 'not_set'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1382, in update_iosapp_battery_information
    self.dev_data_battery_level = int(entity_io.get_state(self.iosapp_entity[BATTERY_LEVEL]))
ValueError: invalid literal for int() with base 10: 'not_set'
2023-01-14 22:08:05.085 ERROR (SyncWorker_10) [icloud3] invalid literal for int() with base 10: 'not_set'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1382, in update_iosapp_battery_information
    self.dev_data_battery_level = int(entity_io.get_state(self.iosapp_entity[BATTERY_LEVEL]))
ValueError: invalid literal for int() with base 10: 'not_set'
2023-01-14 22:08:05.087 ERROR (SyncWorker_10) [icloud3] invalid literal for int() with base 10: 'not_set'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1382, in update_iosapp_battery_information
    self.dev_data_battery_level = int(entity_io.get_state(self.iosapp_entity[BATTERY_LEVEL]))
ValueError: invalid literal for int() with base 10: 'not_set'
2023-01-14 22:08:05.088 ERROR (SyncWorker_10) [icloud3] invalid literal for int() with base 10: 'not_set'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1382, in update_iosapp_battery_information
    self.dev_data_battery_level = int(entity_io.get_state(self.iosapp_entity[BATTERY_LEVEL]))
ValueError: invalid literal for int() with base 10: 'not_set'
```

Also, when trying to EDIT DEVICES in the configuration menu I just get "Unknown error occurred" and the following in the log file:

```
2023-01-14 22:08:00.130 ERROR (SyncWorker_11) [icloud3] invalid literal for int() with base 10: 'not_set'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1382, in update_iosapp_battery_information
    self.dev_data_battery_level = int(entity_io.get_state(self.iosapp_entity[BATTERY_LEVEL]))
ValueError: invalid literal for int() with base 10: 'not_set'
2023-01-14 22:08:00.132 ERROR (SyncWorker_11) [icloud3] invalid literal for int() with base 10: 'not_set'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1382, in update_iosapp_battery_information
    self.dev_data_battery_level = int(entity_io.get_state(self.iosapp_entity[BATTERY_LEVEL]))
ValueError: invalid literal for int() with base 10: 'not_set'
2023-01-14 22:08:00.133 ERROR (SyncWorker_11) [icloud3] invalid literal for int() with base 10: 'not_set'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1382, in update_iosapp_battery_information
    self.dev_data_battery_level = int(entity_io.get_state(self.iosapp_entity[BATTERY_LEVEL]))
ValueError: invalid literal for int() with base 10: 'not_set'
2023-01-14 22:08:00.134 ERROR (SyncWorker_11) [icloud3] invalid literal for int() with base 10: 'not_set'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device.py", line 1382, in update_iosapp_battery_information
    self.dev_data_battery_level = int(entity_io.get_state(self.iosapp_entity[BATTERY_LEVEL]))
ValueError: invalid literal for int() with base 10: 'not_set'
2023-01-14 22:08:00.954 ERROR (MainThread) [icloud3] list index out of range
Traceback (most recent call last):
  File "/config/custom_components/icloud3/config_flow.py", line 2329, in _build_opt_picture_filename_list
    if file.rsplit('.', 1)[1] in image_extensions:
IndexError: list index out of range
2023-01-14 22:08:01.152 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 286, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/icloud3/config_flow.py", line 609, in async_step_menu
    return await self.async_step_device_list()
  File "/config/custom_components/icloud3/config_flow.py", line 1559, in async_step_device_list
    self._build_device_form_selection_lists()
  File "/config/custom_components/icloud3/config_flow.py", line 2136, in _build_device_form_selection_lists
    self._build_opt_famshr_devices_list()
  File "/config/custom_components/icloud3/config_flow.py", line 2150, in _build_opt_famshr_devices_list
    devices_desc = start_ic3.get_famshr_devices(self.PyiCloud)
AttributeError: module 'custom_components.icloud3.support.start_ic3' has no attribute 'get_famshr_devices'
```

Thanks

**Comment by gcobb321** [comment]
@derekoharrow 
1. The first error with the battery info is generated before everything is set up and can be ignored. I have removed the error message from displaying.
2. The get_famshr_devices error has been fixed. I was running b7 code in b8 and it didn't work. Will update to b8a in a few minutes.
FYI-I almost never saw these messages. I am keeping track of problems using the issues page (the bug in the Event Log takes you right to it).Thaw way, things I have to address are in one place rather than scattered around..

Thanks

**Comment by gcobb321** [comment]
I just updated Beta 8 to Beta 8a (Saturday, 6:01PM EST)

- The Configuration was the beta 7 version instead of the beta 8 version. The beta 7 version did not play nice with a lot of things.
- Beta 8 had a problem with the Waze Server selection based on the HA Country Code and you could not select the correct Waze server. The Servers are now alligned with Waze and you can select the one to be used for your location.

Download directly from the [GitHub Code page here](https://github.com/gcobb321/icloud3_v3/blob/main/icloud3-beta-8a.zip). Click download on the right side of the screen.

**Comment by uyuarasy** [comment]
Please add me to the list - uyuarasy

**Comment by B-Hartley** [comment]
Hi,
I'll be testing.
Thanks

**Comment by B-Hartley** [comment]
I don't think I can see a solution above.... Is there a forum I should be posting in for questions.  Just installed the beta.  It seems to be having problems with my country code..

It is set on config.yaml

```
homeassistant:
  country: GB

```
```
2023-01-16 19:29:10.185 ERROR (MainThread) [homeassistant.setup] Error during setup of component icloud3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/icloud3/__init__.py", line 74, in async_setup
    v2v3_config_migration.convert_v2_config_files_to_v3()
  File "/config/custom_components/icloud3/support/v2v3_config_migration.py", line 179, in convert_v2_config_files_to_v3
    self._set_data_fields_from_config_parameter_dictionary()
  File "/config/custom_components/icloud3/support/v2v3_config_migration.py", line 570, in _set_data_fields_from_config_parameter_dictionary
    Gb.conf_general[CONF_WAZE_REGION]                = WAZE_SERVERS_BY_COUNTRY_CODE.get(Gb.ha_country_code, 'row')
AttributeError: type object 'GlobalVariables' has no attribute 'ha_country_code'
```

Please advise.

**Comment by gcobb321** [comment]
When you have a question or an issue, create a new issue on this forum. 

About the country code error, what beta version did you install? Beta 8a is the latest.

**Comment by B-Hartley** [comment]
Thanks. I installed 8a. Problem was in that version.

**Comment by kingy444** [comment]
ive been offline since christmas but just starting to test too

First of all i tried to add via HACS (custom reposiotory pointing to _V3 but versioning isnt avalaible there atm)
I then tried to install Beta 8a from the zip posted

same issue re country code both times - no migration here this is a straight install on a new machine - AU if that matters

```
2023-01-17 10:35:02.296 ERROR (MainThread) [icloud3] type object 'GlobalVariables' has no attribute 'ha_country_code'
File "/config/custom_components/icloud3/__init__.py", line 144, in async_setup_entry
File "/config/custom_components/icloud3/support/v2v3_config_migration.py", line 179, in convert_v2_config_files_to_v3
File "/config/custom_components/icloud3/support/v2v3_config_migration.py", line 570, in _set_data_fields_from_config_parameter_dictionary
2023-01-17 10:35:02.304 ERROR (MainThread) [icloud3] 'NoneType' object has no attribute 'evlog_sensor_state_value'
File "/config/custom_components/icloud3/sensor.py", line 1157, in native_value
```

It asks if you want to setup, then asks what zone and throws the error.
If i hit 'configure' from integrations page i can then continue setup (though i havent been able to get that to work either) - as a side note perhaps need to change this alert type to a confirmation - the current css/display makes it look like an error occurred
![image](https://user-images.githubusercontent.com/7148670/212780608-11601c35-2f02-4948-9936-012f162ef93d.png)

**Comment by kingy444** [comment]
if at all interested (and assuming i can find some time) - if you were to commit the code for v3 to this repository i could potentially provide some assistance in small fixes etc.
I have created HA integrations previously so know what i am doing in that regard

**Comment by gcobb321** [comment]
**iCloud3 Beta 8b update just posted.**

This fixes the problem when migrating from v2 to v3 and getting the ha_country_code not found error message.

If you are already running v3, this update is not needed. Your files have already been migrated.

**Comment by kingy444** [comment]
@gcobb321 found the fix for https://github.com/gcobb321/icloud3_v3/issues/37

appears you commented out and changed the variable name in **__init__.py#247** to
```
Gb.country_code = Gb.ha_location_info.country_code.lower()
Gb.use_metric   = Gb.ha_location_info.use_metric
# Gb.ha_country_code = Gb.ha_location_info.country_code.lower()
# Gb.ha_use_metric   = Gb.ha_location_info.use_metric
```
so that made **support\v2v3_config_migration.py#570** throw an error
changing line 570 from
`
Gb.conf_general[CONF_WAZE_REGION]                = WAZE_SERVERS_BY_COUNTRY_CODE.get(Gb.ha_country_code, 'row')
`
to
`
Gb.conf_general[CONF_WAZE_REGION]                = WAZE_SERVERS_BY_COUNTRY_CODE.get(Gb.country_code, 'row')
`
has fixed that setup issue - onto actually setting up the integration

**Comment by gcobb321** [comment]
I checked every module and 'ha_country_code' is not being used in 8b. I must have missed it before when I went to just 'country_code' for clarity.

**Comment by B-Hartley** [comment]
Sorry to say, it doesn't seem to have fixed the issue.
I deleted the icloud3 folder from custom_components.
Copied in the new one from the 8b beta zip file.
restarted multiple times.

Still getting the same error messages.........

```
2023-01-17 08:26:21.502 WARNING (MainThread) [icloud3] iCloud3 - Migrating Configuration Parameters
2023-01-17 08:26:21.504 ERROR (MainThread) [homeassistant.setup] Error during setup of component icloud3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/icloud3/__init__.py", line 74, in async_setup
    v2v3_config_migration.convert_v2_config_files_to_v3()
  File "/config/custom_components/icloud3/support/v2v3_config_migration.py", line 179, in convert_v2_config_files_to_v3
    self._set_data_fields_from_config_parameter_dictionary()
  File "/config/custom_components/icloud3/support/v2v3_config_migration.py", line 570, in _set_data_fields_from_config_parameter_dictionary
    Gb.conf_general[CONF_WAZE_REGION]                = WAZE_SERVERS_BY_COUNTRY_CODE.get(Gb.ha_country_code, 'row')
AttributeError: type object 'GlobalVariables' has no attribute 'ha_country_code'
2023-01-17 08:26:21.507 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform icloud3.device_tracker: Unable to set up component.
```
Looking at the file v2v3_config_migration, it still has this line in it....

`        Gb.conf_general[CONF_WAZE_REGION]                = WAZE_SERVERS_BY_COUNTRY_CODE.get(Gb.ha_country_code, 'row')`


I changed this to Gb.country_code and it seemed to fix the problem.

**Comment by rdstodda** [comment]
I am testing v3

**Comment by chr04213** [comment]
I'm testing v3,  the only issue that I have is I can't get the zone to display, it shows up on the states for the tracker but the tracker isn't sticking when I assign the tracker to the person.  It works for me but I also have the HA app the other device doesn't at this time.   May not be anything to do with Icloud3.  Under person.name it shows a source: device_tracker.icloud3device for me.  The other person doesn't have that, but the persons configuration file under .storage list that right tracker.  Sorry if this doesn't make sense.

**Comment by gcobb321** [comment]
### Hey guys. I need some help, 
Last night my Rpi froze and I could no longer log into HA. I'm running a Rpi4b-8gb with an SSD (boot & data). I can access the drive via Windows SSH and have copied all code and HA backup files onto my Windows drive so I have everything to do a restore from. I can open a terminal session into the Rpi and have access the Supervisor, poked around and tried to do a restore of a backup but always get a 401 error message (whatever that means, maybe access is not available but I do not know). I've also gotten into the file system with WinSCP but having SSL issues with PuTTY. I'm ready to do a fresh install and start from scratch but hoping someone has an easy way...

I've downloaded a SD image and can burn an SD card. Then reformat the SSD, get the HA image onto the SSD, reboot, restore etc. but hoping there is an easy way to just get the HA image onto the SSD (Maybe plug it into a USB port on my windows computer which I have done and can see the boot partition). 

??? Can I Etcher the HA image directly onto the SSD, put back in the Rpi, start and let HA start rebuilding everything?
??? Or reformat it via Windows so the Rpi will boot off of the SD (hopefully) and go from there.

Thanks

**Comment by B-Hartley** [comment]
Oh no. That sounds like a nightmare. 
I don’t have any experience doing what you are saying. 
If it was me I’d probably do a clean ha install then restore a ha backup and hope all was ok.

**Comment by broyuken** [comment]
401 is an unauthorized error. How did you get the image onto the SSD in the first place? I would recommend doing that again, then upgrading HA to the latest version if your image isn't up to date. Then take a snapshot of the fresh image, then restore the backup. If it fails after the restore, then something probably crapped out in the database or something. If that happens, then restore to the fresh install backup and try to restore an older backup file. You mentioned you have all your yaml files so you shouldn't lose more than maybe some logs.

**Comment by broyuken** [comment]
Are you connecting directly to the ip address or are you going through an nginx reverse proxy or something? If so, try going directly to the ip address:8123 or whatever port you listen on instead.

**Comment by gcobb321** [comment]
I access it using ip::8123 on my win computer. Goint to burn the SSD with the latest HA Rpi image and plug it in and start all over. I remember putting an empty 'network' file in the boot directory of the SSD and checking that out now.

**Comment by gcobb321** [comment]
Beta 9 will be delayed to sometime this weekend, hopefully. My HA had a hard crash and I've spent all day recreating-restoring-updating-backing up-etc. On my third try.

**Comment by gcobb321** [comment]
I just uploaded Beta 9. Download it from the [Release page here](https://github.com/gcobb321/icloud3_v3/releases). Select Assets, then select icloud3-beta-#.zip)

The complete list of changes is on the Releases page but the highlights of this beta are::
- Addresses some zone naming issues
- Fixes a problem where iCloud3 would hang and stop tracking when determining if a near by device can be used for tracking information
- Fixes some battery level/status update problems
- Changes some methods logging into the iCloud account and getting device information when iC3 starts
- Changes some messages and actions in the Event Log (Requires a browser refresh)
- Added an Exclude Sensor screen to select specific sensor entities that should not be created

**Comment by derekoharrow** [comment]
> I just uploaded Beta 9. Download it from the [Release page here](https://github.com/gcobb321/icloud3_v3/releases). Select Assets, then select icloud3-beta-#.zip)
> 
> The complete list of changes is on the Releases page but the highlights of this beta are::
> 
> * Addresses some zone naming issues
> * Fixes a problem where iCloud3 would hang and stop tracking when determining if a near by device can be used for tracking information
> * Fixes some battery level/status update problems
> * Changes some methods logging into the iCloud account and getting device information when iC3 starts
> * Changes some messages and actions in the Event Log (Requires a browser refresh)
> * Added an Exclude Sensor screen to select specific sensor entities that should not be created

It didn't fix this issue for me - I've added a comment. Do you want to re-open it? 

https://github.com/gcobb321/icloud3_v3/issues/42

**Comment by denac** [comment]
denac testing

**Comment by townsmcp** [comment]
I will be testing also

**Comment by myMartek** [comment]
I am also testing. But: I already have seen an issue with updating locations per interval.

I watch 6 devices. And noticed that when a person is moving the update interval might not work anymore. 

Eg. today I noticed that a person was near his work zone and the update interval for his device was 1 minute. But when I looked at it the LastUpdate was over 1.5 hours old. When I manually refreshed the location it did update correctly but then I got `PassThru Zone Delay > Entered zone but may be just passing through, ZoneEntered-CncFertigung, UpdateIn-07:26:35 (1 min)` but still the same: The location is not refreshed even after minutes.

**Comment by gcobb321** [comment]
### Beta 10 was just released

Download it from the [Release page here](https://github.com/gcobb321/icloud3_v3/releases). Select Assets, then select icloud3-beta-#.zip)


This update fixes some problems, adds a few new features and makes some minor changes, The highlights are:
- Added some FamShr & FmF checking to see if data for all configured devices was received from iCloud when starting up. If not, the data request will now be retried up to 2 times instead of giving an error that a device will not be tracked.

- Added an option on the Event Log Parameter screen to display the device's device_tracker zone using the actual zone name or the zone's display_as formatted name.

- Fixed a problem where the Battery and other text based sensors were displaying as numeric fields on the HA History screen.

- The NearBy zone will now only uses location results from tracked devices, monitored devices are no longer used.
- Fixed some problems when 2-devices in the Family Sharing list had the same name.

- And some other minor fixes and tweeks.

Download from the [Release page here](https://github.com/gcobb321/icloud3_v3/releases). Select Assets, then select icloud3-beta-#.zip.
iCloud3 v3 Documentation can be found [here](https://gcobb321.github.io/icloud3_v3_docs/#/)
All of the Change Logs can be found [here](https://github.com/gcobb321/icloud3_v3/blob/v3%2C0%2C0-beta-10/custom_components/icloud3/ChangeLog.txt)

**Comment by hellotomtom** [comment]
I'll be testing

**Comment by beyondwatts** [comment]
Thanks for all your work on this!

> * Fixes a problem where iCloud3 would hang and stop tracking when determining if a near by device can be used for tracking information

This seems to have fixed an issue I was seeing :thumbsup:

One issue I am seeing is that the "Stationary" zone seems to be overriding a named zone from the homeassistant configuration file. Instead of seeing person is at "NamedZone", I am seeing the person is at "Stationary". Is this by design and is there a option to change the behaviour somewhere?

**Comment by gcobb321** [comment]
@beyondwatts I just released beta 10a for that error message. 
On the other Stationary zone problem, will you open a new issue for this. I have some questions and it is easier for me to keep track of problems on the issues page rather than here.

**Comment by beyondwatts** [comment]
Thanks! I have created https://github.com/gcobb321/icloud3_v3/issues/55 please let me know how I can help debug

**Comment by tm24fan8** [comment]
I'll hop in and test as well

**Comment by ChrisBuHa** [comment]
Hi Gary I would also love to test v3.

**Comment by kellya** [comment]
I am trying v3 as of today. 
I apologize if this is covered somewhere, (I didn't see any mention) but I discovered that this can't work with security keys enabled on your appleID, because you don't get a verification code with security keys enabled so you can't proceed to the configuration.  I was able to remove the security keys, and get the verification code as a workaround.

**Comment by ChrisBuHa** [comment]
I must admit, that I‘m quite new to HA but wanted to try icloud3. 
Tried the official icloud integration first but wanted to switch over to icloud3 because of the annoying emails sent whenever HA tried to access my icloud account. 
But with icloud3 I suffered the same issues. 
In addition to the emails I get notifications on my iPhone with a MFA key. But were do I have to isert that key?

**Comment by pauly7300** [comment]
@ChrisBuHa I think you'll get all the info you need regarding the steps on this page in the new documentation area.  https://gcobb321.github.io/icloud3_v3_docs/#/chapters/2.0-installing-and-configuring
Hopefully you can follow this sequence after you get the integration installed which you'll find the steps to in the link above...

<img width="798" alt="image" src="https://user-images.githubusercontent.com/11494052/219207252-8b042199-fe96-4a1a-b0f2-237e3c5550cd.png">

**Comment by bakerkj** [comment]
I'll be testing as well.

**Comment by jodfie** [comment]
jodfie will be testing

**Comment by JeroenTuinstra** [comment]
Just installed it!

**Comment by Nuuki9** [comment]
Been a user of iCloud3 for a couple of years - I've recently found that I've been having to restart it regularly, so came to log an issue only to see there's a v3 beta. Have just installed it and excited to see how it develops.

Thanks for continuing to support this!

**Comment by morrisonpeter** [comment]
I'm trying out v3 beta as well, commenting for notifications as requested. It's working good for me too. Thank you gcob321!

The person badges I use on my dashboard often show the iCloud3 "stationary" zone names instead of my own map zone names or away. I hope I can figure that out (maybe passive zones for iCloud3?). Doesn't look like I can change that, with the HA gui at least. I did see a feature request for this but can't seem to find it now to check that it's for v3. Plus I haven't read all the documentation yet so maybe it's already been addressed. Still searching.

**Comment by gcobb321** [comment]
The Person uses the latitude/longitude attributes of the dev_trkr entity to see what zone they are in. Ic3 should not put a device in a stationary zone when an HA zone exists for the location. Look at the zone that was selected in he Event Log when the tracking results were determined for the device at the time the Stationary zone was created

**Comment by andrzejf1994** [comment]
andrzejf1994 – I will be testing.
I can also make a translation into polish.

**Comment by freekode** [comment]
@freekode singing up for the tests

**Comment by gcobb321** [comment]
@andrzejf1994 Thanks for the offer to translate the Configuration Wizard file. See [here](https://github.com/gcobb321/icloud3_v3/issues/119) for an issue about this.

**Comment by filikun** [comment]
I'm testing v3 right now! :)

**Comment by umrath** [comment]
I will start to test today.

**Comment by japyjaap** [comment]
I am testing V3 since a week or 2.

**Comment by sassyass** [comment]
testing v3 for about a week; it works great so far!

**Comment by stevekuchta** [comment]
Just found the v3 beta. I'm going to switch over this weekend. I was actually a little concerned that this project was being abandoned while looking at the v2 repo. Maybe it may make sense to add a note indicating that v3 is being developed and point to this repo? Though I can understand why you may not want new people installing this version yet.

**Comment by gcobb321** [comment]
I'll do that when it is out of beta. I hope to have beta17 up this weekend. There are a few issues with reauthenticating the iCloud account. It works but you have to restart HA to get around the problem with b16
