### ISSUE TITLE
Still getting "Unknown error occurred" in icloud account login credentials & icloud3 devices review

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3_v3#8]
Still getting this error when starting to review the configuration. This was also present in Beta 1.

![image](https://user-images.githubusercontent.com/11551691/208421099-d308c52a-168e-4af9-b345-d83e16d376f6.png)

**Comment by gcobb321** [comment]
Do any errors show up on HA Settings > System > Logs? 
Did this show up when you first opened this screen or had you selected the ICLOUD ACCOUNT… option?

 I’ll look at the battery_status error.

**Comment by marceloaf** [comment]
Do any errors show up on HA Settings > System > Logs?
 - Not regarding this error. Just the alert to remove the platform: icloud3 statement from configuration.yml

Did this show up when you first opened this screen or had you selected the ICLOUD ACCOUNT… option?
- When selected SENSORS to review and save the options. When I click Save this message shows up.

**Comment by gcobb321** [comment]
The /_config/.storage/icloud3/configuration_ file has a _sensors_ section. There must be a incorrect value in it. Copy and paste it or do a screenshot so I can see what is in it. I’ll add a check to purge invalid entries on startup.

**Comment by marceloaf** [comment]
Hi, this is the sensors section from /config/.storage/icloud3/configuration file:

        "sensors": {
            "monitored_devices": [
                "md_badge",
                "md_battery"
            ],
            "device": [
                "info",
                "battery",
                "battery_status"
            ],
            "tracking_update": [
                "interval",
                "last_located",
                "last_update",
                "next_update"
            ],
            "tracking_time": [
                "travel_time"
            ],
            "tracking_distance": [
                "dir_of_travel",
                "home_distance"
            ],
            "track_from_zones": [
                "tfz_zone_info"
            ],
            "tracking_other": [
                "calc_distance",
                "waze_distance"
            ],
            "zone": [
                "zone",
                "zone_name"
            ],
            "other": [],
            "tracking_by_zones": []
        }

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by marceloaf** [comment]
Hello. After a restart I got the error below on HA logs. Maybe it can help somehow.

-------------------------------
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/icloud3/helpers/common.py:121
Integration: iCloud3 Device Tracker (documentation, issues)
First occurred: 11:52:57 (1 occurrences)
Last logged: 11:52:57

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/icloud3/config_flow.py", line 565, in async_step_menu
    return await self.async_step_icloud_account()
  File "/config/custom_components/icloud3/config_flow.py", line 1262, in async_step_icloud_account
    data_schema=self.form_schema(self.step_id),
  File "/config/custom_components/icloud3/config_flow.py", line 3002, in form_schema
    else obscure_field(self.password)
  File "/config/custom_components/icloud3/helpers/common.py", line 121, in obscure_field
    email_name, email_domain = field.split('@')
ValueError: too many values to unpack (expected 2)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Marcelo ***@***.***>
Sent: segunda-feira, 19 de dezembro de 2022 10:57
To: ***@***.***>
Subject: RE: [gcobb321/icloud3_v3] Still getting "Unknown error occurred" in icloud account login credentials & icloud3 devices review (Issue #8)

Hi, this is the sensors section from /config/.storage/icloud3/configuration file:

        "sensors": {
            "monitored_devices": [
                "md_badge",
                "md_battery"
            ],
            "device": [
                "info",
                "battery",
                "battery_status"
            ],
            "tracking_update": [
                "interval",
                "last_located",
                "last_update",
                "next_update"
            ],
            "tracking_time": [
                "travel_time"
            ],
            "tracking_distance": [
                "dir_of_travel",
                "home_distance"
            ],
            "track_from_zones": [
                "tfz_zone_info"
            ],
            "tracking_other": [
                "calc_distance",
                "waze_distance"
            ],
            "zone": [
                "zone",
                "zone_name"
            ],
            "other": [],
            "tracking_by_zones": []
        }

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by gcobb321** [comment]
Delete the _"tracking_by_zones": []_ item at the bottom of the list and the comma at the end of the line above it so it reads _"other": []_

**Comment by gcobb321** [comment]
Also delete the _"battery_status" line and the comma at the end of the line above it from the _Devices_ section so it looks like:
 ```
"device": [
                "info",
                "battery
],
```

**Comment by gcobb321** [comment]
Are you running beta 1 or beta 2? I was hoping to have the _Blocking calls must be done in the executor..._ fixed in beta 2.

**Comment by marceloaf** [comment]
I’m running beta 2

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Gary Cobb ***@***.***>
Enviado: Monday, December 19, 2022 2:34:53 PM
Para: gcobb321/icloud3_v3 ***@***.***>
Cc: marceloaf ***@***.***>; Author ***@***.***>
Assunto: Re: [gcobb321/icloud3_v3] Still getting "Unknown error occurred" in icloud account login credentials & icloud3 devices review (Issue #8)


Are you running beta 1 or beta 2? I was hoping to have the Blocking calls must be done in the executor... fixed in beta 2.

**Comment by gcobb321** [comment]
I think this is fixed in beta 3. I’ll close this issue when beta 3 is available.

**Comment by gcobb321** [comment]
Ho Ho Ho. Happy holidays. 🎄🎅

If you don’t have plans, enjoy [iCloud3 v3.0.0 beta 3](https://github.com/gcobb321/icloud3_v3/releases)

Gary
